services:
  picamera:
    image: harbor.vcloud.nii.ac.jp/sinetstream/sensor-picamera:0.3.0
    privileged: true
    volumes:
      - /dev:/dev
      - /run/udev:/run/udev
    restart: on-failure:5
    env_file: .env
