services:
  broker:
    image: apache/kafka:3.8.0
    hostname: kafka0
    environment:
      KAFKA_NODE_ID: "10"
      KAFKA_PROCESS_ROLES: broker
      KAFKA_ADVERTISED_LISTENERS: BROKER://${BROKER_HOSTNAME}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: BROKER:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_DEFAULT_REPLICATION_FACTOR: "1"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1000@controller:9093
      KAFKA_LOG_DIR: /var/lib/kafka/data
      #CLUSTER_ID: ${CLUSTER_ID}
    #volumes:
    #  - "./broker/data:/var/lib/kafka/data"
    depends_on:
      - controller
    ports:
      - 9092:9092
    restart: on-failure:3
  controller:
    image: apache/kafka:3.8.0
    hostname: controller
    environment:
      KAFKA_NODE_ID: "1000"
      KAFKA_PROCESS_ROLES: controller
      KAFKA_LISTENERS: CONTROLLER://:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1000@controller:9093
      KAFKA_LOG_DIR: /var/lib/kafka/data
      #CLUSTER_ID: ${CLUSTER_ID}
    #volumes:
    #  - "./controller/data:/var/lib/kafka/data"
    restart: on-failure:3
